steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--no-cache"
      - "-t"
      - "gcr.io/$PROJECT_ID/teomebot:$COMMIT_SHA"
      - "-t"
      - "gcr.io/$PROJECT_ID/teomebot:latest"
      - "."
      - "- Dockerfile"
    id: Build

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/teomebot:$COMMIT_SHA"
    id: Push
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/teomebot:latest"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    args:
      - "compute"
      - "instances"
      - "update-container"
      - "teomebot-instance"
      - "--container-image=gcr.io/$PROJECT_ID/teomebot:latest"
      - "--zone=$_DEPLOY_ZONE"
      - "--container-restart-policy=always"

options:
  logging: CLOUD_LOGGING_ONLY
